export interface MainItemsProps {
  items: ItemProps[];
}

type ItemProps = {
  image: string;
  QRcode: string;
  largeHeader: string;
  smallHeader: string;
  body: string;
  firstHeader: string;
  firstBody: string;
  secondHeader: string;
  secondBody: string;
  thirdHeader: string;
  thirdBody: string;
  lastText: string;
  Noise: string;
};
export const MockItems = [
  {
    image: "originalAvatarGirl.svg",
    QRcode: "QRcode.svg",
    largeHeader: "WEB3 Watch Party",
    smallHeader: "STARTS",
    body: "12:00 23 Jul 2024",
    firstHeader: "ROW/SEAT",
    firstBody: "A/12",
    secondHeader: "GATE",
    secondBody: "South",
    thirdHeader: "VENUE",
    thirdBody: "Main Hall",
    lastText: "EVENTMINT",
    Noise: "/Noisepng.png",
  },
  {
    image: "/eth.svg",
    QRcode: "QRcode.svg",
    largeHeader: "Ethereum Boom?",
    smallHeader: "STARTS",
    body: "01:00 10 Aug 2024",
    firstHeader: "ROW/SEAT",
    firstBody: "C/11",
    secondHeader: "GATE",
    secondBody: "East",
    thirdHeader: "VENUE",
    thirdBody: "Event Hall",
    lastText: "EVENTMINT",
    Noise: "/Noisepng.png",
  },
  {
    image: "/AvatarGuy2.svg",
    QRcode: "QRcode.svg",
    largeHeader: "Joshua’s Space",
    smallHeader: "STARTS",
    body: "01:00 23 Jul 2024",
    firstHeader: "ROW/SEAT",
    firstBody: "C/09",
    secondHeader: "GATE",
    secondBody: "North",
    thirdHeader: "VENUE",
    thirdBody: "Event Hall",
    lastText: "EVENTMINT",
    Noise: "/Noisepng.png",
  },
  {
    image: "/avatarBubble2.svg",
    QRcode: "QRcode.svg",
    largeHeader: "Talk about Crypto",
    smallHeader: "STARTS",
    body: "12:00 23 Jul 2024",
    firstHeader: "ROW/SEAT",
    firstBody: "A/12",
    secondHeader: "GATE",
    secondBody: "South",
    thirdHeader: "VENUE",
    thirdBody: "Main Hall",
    lastText: "EVENTMINT",
    Noise: "/Noisepng.png",
  },
  {
    image: "Avatargirl3.svg",
    QRcode: "QRcode.svg",
    largeHeader: "My Twitch Space",
    smallHeader: "STARTS",
    body: "19:00 25 Dec 2024",
    firstHeader: "ROW/SEAT",
    firstBody: "B/01",
    secondHeader: "GATE",
    secondBody: "West",
    thirdHeader: "VENUE",
    thirdBody: "Main Hall",
    lastText: "EVENTMINT",
    Noise: "/Noisepng.png",
  },
  {
    image: "/avatarBubble2.svg",
    QRcode: "QRcode.svg",
    largeHeader: "Ecosystem Call",
    smallHeader: "STARTS",
    body: "15:00 09 Sep 2024",
    firstHeader: "ROW/SEAT",
    firstBody: "A/12",
    secondHeader: "GATE",
    secondBody: "South",
    thirdHeader: "VENUE",
    thirdBody: "Main Hall",
    lastText: "EVENTMINT",
    Noise: "/Noisepng.png",
  },
  {
    image: "/eth.svg",
    QRcode: "QRcode.svg",
    largeHeader: "Ethereum Boom?",
    smallHeader: "STARTS",
    body: "01:00 10 Aug 2024",
    firstHeader: "ROW/SEAT",
    firstBody: "C/11",
    secondHeader: "GATE",
    secondBody: "East",
    thirdHeader: "VENUE",
    thirdBody: "Event Hall",
    lastText: "EVENTMINT",
    Noise: "/Noisepng.png",
  },
  {
    image: "originalAvatarGirl.svg",
    QRcode: "QRcode.svg",
    largeHeader: "WEB3 Watch Party",
    smallHeader: "STARTS",
    body: "12:00 23 Jul 2024",
    firstHeader: "ROW/SEAT",
    firstBody: "A/12",
    secondHeader: "GATE",
    secondBody: "South",
    thirdHeader: "VENUE",
    thirdBody: "Main Hall",
    lastText: "EVENTMINT",
    Noise: "/Noisepng.png",
  },
  {
    image: "/avatarBubble2.svg",
    QRcode: "QRcode.svg",
    largeHeader: "Talk about Crypto",
    smallHeader: "STARTS",
    body: "12:00 23 Jul 2024",
    firstHeader: "ROW/SEAT",
    firstBody: "A/12",
    secondHeader: "GATE",
    secondBody: "South",
    thirdHeader: "VENUE",
    thirdBody: "Main Hall",
    lastText: "EVENTMINT",
    Noise: "/Noisepng.png",
  },
  {
    image: "/AvatarGuy2.svg",
    QRcode: "QRcode.svg",
    largeHeader: "Joshua’s Space",
    smallHeader: "STARTS",
    body: "01:00 23 Jul 2024",
    firstHeader: "ROW/SEAT",
    firstBody: "C/09",
    secondHeader: "GATE",
    secondBody: "North",
    thirdHeader: "VENUE",
    thirdBody: "Event Hall",
    lastText: "EVENTMINT",
    Noise: "/Noisepng.png",
  },
  {
    image: "Avatargirl3.svg",
    QRcode: "QRcode.svg",
    largeHeader: "My Twitch Space",
    smallHeader: "STARTS",
    body: "19:00 25 Dec 2024",
    firstHeader: "ROW/SEAT",
    firstBody: "B/01",
    secondHeader: "GATE",
    secondBody: "West",
    thirdHeader: "VENUE",
    thirdBody: "Main Hall",
    lastText: "EVENTMINT",
    Noise: "/Noisepng.png",
  },
];
